### ISSUE TITLE
Add enter user own Youtube API Key option

### ISSUE THREAD

**Issue by Iz-zzzzz** [knightron0/tempus#13]
Add enter user own Youtube API Key option

**Comment by knightron0** [comment]
You can technically clone the repository, put your own API key in, and load the extension to your browser to use – it just won't be through the Chrome Web Store. 

Just curious (and looking for more context), why do you want to do so? Are there some issues with the current key for you?

**Comment by Iz-zzzzz** [comment]
Sometimes the extension doesn't load comment (I wait for 10+ mins until the video ends) and kind of this extension usually facing an API quota limit. So I think this extension might has the same issue too.

**Comment by roshank231** [comment]
I was wondering the same thing.

Is it possible to show some sort of loading indicator to see if the extension is hitting a quota or hanging? I also find it to just be stuck loading for some time, sometimes only showing up after a refresh.

**Comment by knightron0** [comment]
Interesting, I think this might be more of a sync issue where the extension doesn't properly detect the video and doesn't start loading the comments. I've noticed something similar at times since the last update to the codebase -- I'll check it out!

**Comment by NicPalacio** [comment]
@knightron0  Hi guys can You please explain how to do the process to run the extension with my API, the extension si not working and for what Ive seen it seems a quota limited problem because it only charges some few tiemstamped comments sometimes. I don't have much tehcnical knowledge so would really appreciate if you asssit me briefly how could I use my API. Thank you!.

**Comment by mdhsieh** [comment]
@NicPalacio if you do want to use your own API key, you would start with [this guide](https://developers.google.com/youtube/v3/getting-started):

1. Sign into [Google Cloud Console](https://console.cloud.google.com/) and select or make a new project.
2. For the project, enable the [YouTube Data v3 API](https://console.cloud.google.com/apis/api/youtube.googleapis.com/), save and copy the secret key.
3. Follow the [contributing](https://github.com/knightron0/tempus?tab=readme-ov-file#contributing) instructions and paste in your key.

**Comment by mdhsieh** [comment]
@Iz-zzzzz late reply but the sync issue is still happening right?

Does anyone have ideas how to reproduce it?

**Comment by mdhsieh** [comment]
@knightron0 Not sure how you want to proceed, but to enter own API keys maybe start with something like #16?

I don't know how to get the sync issue.
