### ISSUE TITLE
Not Working for me recently

### ISSUE THREAD

**Issue by NicPalacio** [knightron0/tempus#14]
Hi ! can You please explain how to do the process to run the extension with my API, the extension is not working and for what Ive seen it seems a quota limited problem because it only charges some few tiemstamped comments sometimes. I don't have much tehcnical knowledge so would really appreciate if you asssit me briefly how could I use my API. Thank you!.

![image](https://github.com/knightron0/tempus/assets/134461451/ecfe6a1e-fd37-4326-ad0a-73318b66bc45)

**Comment by knightron0** [comment]
unfortunately, this error means that the given YT video doesn't have any comments with timestamps (no user has commented a timestamp). it doesn't relate to the quota issue :/

**Comment by NicPalacio** [comment]
Hi @knightron0 thanks for your response !. However, the issue persists. It worked wonders, but since around November, it has stopped functioning. I am sure that the video does have comments with timestamps, so I believe the problem is other. Do you have any ideas about what it could be? It seems to only work for videos with very few comments, with some of them having timestamps such as the demonstration video but if the video have less say more than 100 comments it does not works 😢 .

Thank you for your help.

**Comment by knightron0** [comment]
my bad — yes it's stopped working. really sorry, ill try pushing a fix soon. 

on the other hand, if you want to run it with your own YouTube API, refer to the contributing heading in the readme (basically load the extension from your local computer instead of from the chrome web store). however — i don't seem to be seeing issues with the API on the dashboard, it's somewhere else :/

**Comment by NicPalacio** [comment]
Exactly @knightron0 the problem is somewhere else because I did the process to use my own API and it does not worked either.

Thank you for noticing the problem , hope you can fixed it , I'll be awaiting your update.

**Comment by TrentF94** [comment]
I have had the same issue for a couple months now, except I cant get a single timestamped comment to show in the replay even when I can clearly find timestamps in the comment section. I have looked for alternative extensions but there is nothing with such a real-time playback of timestamped comments. It has really improved my experience on YouTube and watching videos isn't the same recently.


Thank you for your time.

**Comment by NicPalacio** [comment]
@knightron0 , @TrentF94 I completely agree, the extension significantly enhances the experience, especially for longer videos. It's a shame that it's not working anymore. 😢

**Comment by TrentF94** [comment]
I have recently had the comments load for some videos. Did you just implement a fix?

**Comment by NicPalacio** [comment]
Hi @knightron0 ! How's it going? Sorry to bother you; I just wanted to know if you have any updates on the matter or if you've been able to identify the root of the problem. I would love to help in any way I can. I really miss the extension 😢 .

**Comment by TrentF94** [comment]
Hey I only ever had it load comments for one video. I've tried fresh
installing Chrome and disabling other extensions just in case they were
conflicting. It seems to be something with the comments not being compiled
by the extension idk if it is a recent change to YouTube because I know
they are trying to stop ad blockers so maybe they are blocking certain
extensions.

Let me know if you can find a solution because it really is a great
extension.

**Comment by NicPalacio** [comment]
@knightron0  Hi men how are you doing,  any update about the problem ?

**Comment by TrentF94** [comment]
No changes for me it hasn't worked since

**Comment by knightron0** [comment]
Yeah -- I just investigated. It seems like an issue with the searchTerms query I was throwing into YouTube's API (see #3). I have a few ideas on how to fix it as well, hopefully, I can implement them in the next few days.

**Comment by TrentF94** [comment]
Thank you I really appreciate you following up on it because honestly this
is probably my favorite youtube extension because I can see real time
reactions and corrections on videos.

**Comment by NicPalacio** [comment]
@TrentF94 , @knightron0  Hi guys,  any update ? For me to date, it still doesn't work. Is it working for you yet?"

**Comment by TrentF94** [comment]
I just had it work for an older movie trailer. Are there any updates?

**Comment by mdhsieh** [comment]
Hey @knightron0 I have opened a PR #15 , can you let me know if that would work with you?

**Comment by TrentF94** [comment]
The extension just started working again today after reinstalling. I will update if it stops working but it seems to be gathering most if not all of the timestamped comments. Thank you! :)
