### ISSUE TITLE
Add alternating colors to chat

### ISSUE THREAD

**Issue by azizLIGHT** [knightron0/tempus#4]
In comments replay view, adding alternating background color for each timestamp/comment could help visibility. Maybe it could be an option, and off by default. What do you think?

**Comment by knightron0** [comment]
This is pretty late – but this is a great idea! I'll work on implementing this soon.

**Comment by knightron0** [comment]
Added basic functionality (without customizability) in [dac2787](https://github.com/knightron0/tempus/commit/dac2787e2b2ae1f6139c3a929a8840e477aca9f7).
